# Generated by Django 4.0.6 on 2022-07-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MICROGLIA', 'Microglie'), ('MENINGE', 'Méninge')], default=None, max_length=25, null=True)),
                ('current_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.cell')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.position')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='current_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.position'),
        ),
    ]
