# Generated by Django 4.0.6 on 2022-07-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='current_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.position'),
        ),
    ]
