# Generated by Django 4.0.6 on 2022-07-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_cell_current_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='type',
            field=models.CharField(choices=[('MICROGLIA', 'Microglie'), ('MENINGE', 'Méninge')], default=None, max_length=25),
        ),
    ]
