# Generated by Django 4.0.6 on 2022-07-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_cell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stats.position'),
        ),
    ]
